// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nydznnfkvzlrprpkaymo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55ZHpubmZrdnpscnBycGtheW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDMwMzQsImV4cCI6MjA2MTE3OTAzNH0.ZVH9W7VjYdnGag4pd1BkBZfyQjZ870hbA2mf8qYUyVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);